if(EXISTS "/home/randy/QSat/build-debug/unittests/verify_basics_tests-b858cb2.cmake")
  include("/home/randy/QSat/build-debug/unittests/verify_basics_tests-b858cb2.cmake")
else()
  add_test(verify_basics_NOT_BUILT-b858cb2 verify_basics_NOT_BUILT-b858cb2)
endif()
