if(EXISTS "/home/randy/QSat/build-debug/unittests/verify_watches_tests-b858cb2.cmake")
  include("/home/randy/QSat/build-debug/unittests/verify_watches_tests-b858cb2.cmake")
else()
  add_test(verify_watches_NOT_BUILT-b858cb2 verify_watches_NOT_BUILT-b858cb2)
endif()
